config/routes.rb
Rails.application.routes.draw do

  
  root "boards#index"

  devise_for :users

  resources :boards do
    resources :artists
  end

  resources :artists do
    resources :songs 
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    belongs_to :board
    has_many :songs
end

app/models/board.rb
class Board < ApplicationRecord
    has_many :artists
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      end
end

    

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, except: [:index, :new, :create]
  
  def index
    @artists = Artist.all
  end

  def show
    @songs = @artist.songs.all
    @board = Board.find(params[:board_id])
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def edit
    #render :edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to artists_path
    else
      render :edit
    end
  end

  private
    def artist_params
      params.require(:artist).permit(:name)
    end

    def set_artist
      @artist = Artist.find(params[:id])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, except: [:index, :new, :create]

  def index
    @boards = Board.all.order("name")
  end

  def show
    @artists = @board.artists.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def edit
    #render :edit
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, except: [:index, :new, :create]
  
  def index
    @songs = Song.all
  end

  def show
    #render :show
  end

  def new
    @song = Song.new()
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to artist_song_path(@artist, @song)
    else
      render :new
    end
  end

  def edit
    #render :edit
  end

  def update
    if @song.update(song_params)
      redirect_to artist_song_path(@artist, @song)
    else
      render :edit
    end
  end

  private
    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1 class="section-title"><%= @artist.name %></h1>

<table>
    <tr>
        <th>Album No.</th>
        <th>Album Name</th>
    </tr>
    <% @counter = 1 %>
    <% @artist.songs.each do |song|%>
        <tr>
            <td><%= @counter %></td>
            <td><%= song.name %></td>
        </tr>
        <% @counter += 1 %>
    <% end %>
</table>


<%= link_to "Back", board_path(@board), class:"body-button"%>

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true, class: "form") do |f| %>
    <%= f.text_field :name, required: true, placeholder: "Board Name:", class: "name-field" %>
    <%= f.submit "Submit", class:"submit"%>
<% end %>

app/views/boards/edit.html.erb
<h1 class="section-title">Edit Board Name</h1>

<%= render "form", board: @board %>

<%= link_to "Back", boards_path, class:"body-button"%>

app/views/boards/index.html.erb
<div class="board-container">
    <% @boards.each do |board| %>
        <%= link_to board_path(board), :index => 'go' do %>
            <div class="board">
                <%= board.name %>
            </div>
        <% end %>
    <% end %>
</div>
<%= link_to "Create Board", new_board_path, class: "body-button" %>

app/views/boards/new.html.erb
<h1 class="section-title">New Board</h1>

<%= render "form", board: @board %>

<div class="back">
    <%= link_to "Back", boards_path %>
</div>

app/views/boards/show.html.erb
<h1 class="page-title">Top 100 <%= " #{@board.name}" %></h1>
<table>
    <thead>
    </thead>
    <tbody>
        <tr>
            <th>Position</th>
            <th>Artist</th>
        </tr>
        <% @counter = 1 %>
        <% @artists.each do | artist | %>
            <tr>
                <td><%= @counter %></td>
                <td><%= link_to artist.name, board_artist_path(@board, artist) %></td>
            </tr>
            <% @counter += 1 %>
        <% end %>
        
    </tbody>
</table>
<%= link_to "Edit Board Name", edit_board_path(@board), class: "body-button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TopBillboards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag asset_path('favicon-music'), :rel => 'icon', :type =>  'image/ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navigation">
      <ul>
          <% if user_signed_in? %>
            <li class="welcome"><%= "Welcome #{current_user.first_name}" %></li>
          <% end %>
          <%= link_to "Boards", boards_path %>
          <% if user_signed_in? %>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% end %>
      </ul>
    </div>
    <div class="site-wrapper">
      <%= yield %>
    </div>
  </body>
</html>